# ansible/inventory.ini
# ----------------------
# Static inventory for local testing.
# Replace WINDOWS_PUBLIC_IP with the output of:
#   cd terraform && terraform output -raw public_ip

[windows]
44.211.34.102

[windows:vars]
ansible_user=ansible_admin
ansible_password=MyStr0ngP@ss2024!
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_port=5985
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore
ansible_winrm_operation_timeout_sec=120
ansible_winrm_read_timeout_sec=150
